// <auto-generated />
using System;
using System.Collections.Generic;
using GitGudModsListLoader.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitGudModsListLoader.Migrations;

[DbContext(typeof(ModsDbContext))]
partial class ModsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("GitGudModsListLoader.Persistence.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Order")
                    .HasColumnType("integer");

                b.Property<int?>("ParentId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.HasIndex("ParentId");

                b.ToTable("Category");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "Animations",
                        Order = 0
                    },
                    new
                    {
                        Id = 2,
                        Name = "Armour",
                        Order = 0
                    },
                    new
                    {
                        Id = 3,
                        Name = "Audio",
                        Order = 0
                    },
                    new
                    {
                        Id = 4,
                        Name = "Cities",
                        Order = 0,
                        ParentId = 12
                    },
                    new
                    {
                        Id = 5,
                        Name = "Clothing",
                        Order = 0
                    },
                    new
                    {
                        Id = 6,
                        Name = "Collectables",
                        Order = 0
                    },
                    new
                    {
                        Id = 7,
                        Name = "Creatures, Mounts, & Vehicles",
                        Order = 0
                    },
                    new
                    {
                        Id = 8,
                        Name = "Factions",
                        Order = 0
                    },
                    new
                    {
                        Id = 9,
                        Name = "Gameplay",
                        Order = 0
                    },
                    new
                    {
                        Id = 10,
                        Name = "Body, Face, & Hair",
                        Order = 0
                    },
                    new
                    {
                        Id = 11,
                        Name = "Items",
                        Order = 0
                    },
                    new
                    {
                        Id = 12,
                        Name = "Locations",
                        Order = 0
                    },
                    new
                    {
                        Id = 13,
                        Name = "NPCs",
                        Order = 0
                    },
                    new
                    {
                        Id = 14,
                        Name = "Patches",
                        Order = 0,
                        ParentId = 24
                    },
                    new
                    {
                        Id = 15,
                        Name = "Quests",
                        Order = 0
                    },
                    new
                    {
                        Id = 16,
                        Name = "Races & Classes",
                        Order = 0
                    },
                    new
                    {
                        Id = 17,
                        Name = "UI",
                        Order = 0
                    },
                    new
                    {
                        Id = 18,
                        Name = "Visuals",
                        Order = 0
                    },
                    new
                    {
                        Id = 19,
                        Name = "Weapons",
                        Order = 0,
                        ParentId = 11
                    },
                    new
                    {
                        Id = 20,
                        Name = "Magic",
                        Order = 0
                    },
                    new
                    {
                        Id = 21,
                        Name = "Models & Textures",
                        Order = 0
                    },
                    new
                    {
                        Id = 22,
                        Name = "Skills & Levelling",
                        Order = 0,
                        ParentId = 9
                    },
                    new
                    {
                        Id = 23,
                        Name = "Player Homes",
                        Order = 0
                    },
                    new
                    {
                        Id = 24,
                        Name = "Bugfixes",
                        Order = 0
                    },
                    new
                    {
                        Id = 25,
                        Name = "Castles & Mansions",
                        Order = 0,
                        ParentId = 23
                    },
                    new
                    {
                        Id = 26,
                        Name = "Cheats",
                        Order = 0
                    },
                    new
                    {
                        Id = 27,
                        Name = "Combat",
                        Order = 0,
                        ParentId = 9
                    },
                    new
                    {
                        Id = 28,
                        Name = "Companions",
                        Order = 0
                    },
                    new
                    {
                        Id = 29,
                        Name = "Environment",
                        Order = 0
                    },
                    new
                    {
                        Id = 30,
                        Name = "Immersion",
                        Order = 0
                    },
                    new
                    {
                        Id = 31,
                        Name = "Landscape Changes",
                        Order = 0
                    },
                    new
                    {
                        Id = 32,
                        Name = "Mercantile",
                        Order = 0
                    },
                    new
                    {
                        Id = 33,
                        Name = "Modders resources",
                        Order = 0
                    },
                    new
                    {
                        Id = 34,
                        Name = "Stealth",
                        Order = 0
                    },
                    new
                    {
                        Id = 35,
                        Name = "Utilities",
                        Order = 0
                    },
                    new
                    {
                        Id = 36,
                        Name = "Weapon & Armour Sets",
                        Order = 0,
                        ParentId = 11
                    },
                    new
                    {
                        Id = 37,
                        Name = "Ammo",
                        Order = 0,
                        ParentId = 11
                    },
                    new
                    {
                        Id = 38,
                        Name = "Music",
                        Order = 0
                    },
                    new
                    {
                        Id = 39,
                        Name = "Voice",
                        Order = 0
                    },
                    new
                    {
                        Id = 40,
                        Name = "Character Presets",
                        Order = 0
                    },
                    new
                    {
                        Id = 41,
                        Name = "Jewelry",
                        Order = 0,
                        ParentId = 5
                    },
                    new
                    {
                        Id = 42,
                        Name = "Backpacks",
                        Order = 0,
                        ParentId = 5
                    },
                    new
                    {
                        Id = 43,
                        Name = "Crafting",
                        Order = 0,
                        ParentId = 9
                    },
                    new
                    {
                        Id = 44,
                        Name = "Equipment",
                        Order = 0,
                        ParentId = 43
                    },
                    new
                    {
                        Id = 45,
                        Name = "Home/Settlement",
                        Order = 0,
                        ParentId = 43
                    },
                    new
                    {
                        Id = 46,
                        Name = "Shader Presets",
                        Order = 0
                    },
                    new
                    {
                        Id = 47,
                        Name = "Miscellaneous",
                        Order = 0
                    },
                    new
                    {
                        Id = 48,
                        Name = "Overhauls",
                        Order = 0,
                        ParentId = 9
                    },
                    new
                    {
                        Id = 49,
                        Name = "Perks",
                        Order = 0,
                        ParentId = 9
                    },
                    new
                    {
                        Id = 51,
                        Name = "Settlements",
                        Order = 0,
                        ParentId = 23
                    },
                    new
                    {
                        Id = 52,
                        Name = "Poses",
                        Order = 0
                    },
                    new
                    {
                        Id = 53,
                        Name = "Power Armor",
                        Order = 0,
                        ParentId = 2
                    },
                    new
                    {
                        Id = 54,
                        Name = "Radio",
                        Order = 0,
                        ParentId = 9
                    },
                    new
                    {
                        Id = 55,
                        Name = "Shouts",
                        Order = 0,
                        ParentId = 9
                    },
                    new
                    {
                        Id = 56,
                        Name = "Tattoos",
                        Order = 0,
                        ParentId = 10
                    },
                    new
                    {
                        Id = 58,
                        Name = "Weather & Lighting",
                        Order = 0,
                        ParentId = 9
                    });
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.Mod", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Author")
                    .HasColumnType("text");

                b.Property<Dictionary<string, string>>("Metadata")
                    .IsRequired()
                    .HasColumnType("hstore");

                b.Property<string>("MetadataPath")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PackageType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PreviewUrl")
                    .HasColumnType("text");

                b.Property<long>("ProjectId")
                    .HasColumnType("bigint");

                b.Property<int>("Stars")
                    .HasColumnType("integer");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Mods");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.ModDependency", b =>
            {
                b.Property<int>("ModId")
                    .HasColumnType("integer");

                b.Property<int>("DependencyModId")
                    .HasColumnType("integer");

                b.HasKey("ModId", "DependencyModId");

                b.HasIndex("DependencyModId");

                b.ToTable("ModDependency");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.ModTitle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("ModId")
                    .HasColumnType("integer");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("ModId", "Title")
                    .IsUnique();

                b.ToTable("ModTitle");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.ModToCategory", b =>
            {
                b.Property<int>("ModId")
                    .HasColumnType("integer");

                b.Property<int>("CategoryId")
                    .HasColumnType("integer");

                b.HasKey("ModId", "CategoryId");

                b.HasIndex("CategoryId");

                b.ToTable("ModToCategory");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.ModVersion", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("ModId")
                    .HasColumnType("integer");

                b.PrimitiveCollection<string[]>("Urls")
                    .IsRequired()
                    .HasColumnType("text[]");

                b.Property<string>("Version")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("ModId", "Version")
                    .IsUnique();

                b.ToTable("ModVersion");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.Category", b =>
            {
                b.HasOne("GitGudModsListLoader.Persistence.Category", "Parent")
                    .WithMany()
                    .HasForeignKey("ParentId");

                b.Navigation("Parent");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.ModDependency", b =>
            {
                b.HasOne("GitGudModsListLoader.Persistence.Mod", "DependencyMod")
                    .WithMany("RequiredBy")
                    .HasForeignKey("DependencyModId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("GitGudModsListLoader.Persistence.Mod", "Mod")
                    .WithMany("Dependencies")
                    .HasForeignKey("ModId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("DependencyMod");

                b.Navigation("Mod");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.ModTitle", b =>
            {
                b.HasOne("GitGudModsListLoader.Persistence.Mod", "Mod")
                    .WithMany("Titles")
                    .HasForeignKey("ModId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Mod");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.ModToCategory", b =>
            {
                b.HasOne("GitGudModsListLoader.Persistence.Category", "Category")
                    .WithMany("ModCategories")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("GitGudModsListLoader.Persistence.Mod", "Mod")
                    .WithMany("ModCategories")
                    .HasForeignKey("ModId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Category");

                b.Navigation("Mod");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.ModVersion", b =>
            {
                b.HasOne("GitGudModsListLoader.Persistence.Mod", "Mod")
                    .WithMany("Versions")
                    .HasForeignKey("ModId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Mod");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.Category", b =>
            {
                b.Navigation("ModCategories");
            });

        modelBuilder.Entity("GitGudModsListLoader.Persistence.Mod", b =>
            {
                b.Navigation("Dependencies");

                b.Navigation("ModCategories");

                b.Navigation("RequiredBy");

                b.Navigation("Titles");

                b.Navigation("Versions");
            });
#pragma warning restore 612, 618
    }
}
